2020-01-09 19:16:35,134 p=wid u=1715 | ERROR! the playbook: log could not be found
2020-01-09 19:16:37,375 p=wid u=1721 | PLAY [ansible logrotate] ****************************************************************
2020-01-09 19:16:37,385 p=wid u=1721 | TASK [Gathering Facts] ******************************************************************
2020-01-09 19:16:37,466 p=wid u=1721 | fatal: [localhost]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'localhost' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey,password).", "unreachable": true}
2020-01-09 19:16:37,468 p=wid u=1721 | PLAY RECAP ******************************************************************************
2020-01-09 19:16:37,468 p=wid u=1721 | localhost                  : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
2020-01-09 19:16:52,514 p=wid u=1733 | ERROR! the playbook: , could not be found
2020-01-09 19:16:59,434 p=wid u=1735 | PLAY [ansible logrotate] ****************************************************************
2020-01-09 19:16:59,439 p=wid u=1735 | TASK [Gathering Facts] ******************************************************************
2020-01-09 19:16:59,888 p=wid u=1735 | fatal: [localhost]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "deprecations": [{"msg": "Distribution Ubuntu 16.04 on host localhost should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", "version": "2.12"}], "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: setup\n"}
2020-01-09 19:16:59,891 p=wid u=1735 | PLAY RECAP ******************************************************************************
2020-01-09 19:16:59,891 p=wid u=1735 | localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-01-09 19:17:27,329 p=wid u=1780 | PLAY [ansible logrotate] ****************************************************************
2020-01-09 19:17:27,335 p=wid u=1780 | TASK [Gathering Facts] ******************************************************************
2020-01-09 19:17:27,671 p=wid u=1780 | fatal: [localhost]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "deprecations": [{"msg": "Distribution Ubuntu 16.04 on host localhost should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", "version": "2.12"}], "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: setup\n"}
2020-01-09 19:17:27,672 p=wid u=1780 | PLAY RECAP ******************************************************************************
2020-01-09 19:17:27,672 p=wid u=1780 | localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-01-09 19:18:07,567 p=wid u=1840 | PLAY [ansible logrotate] ****************************************************************
2020-01-09 19:18:07,573 p=wid u=1840 | TASK [Gathering Facts] ******************************************************************
2020-01-09 19:18:07,904 p=wid u=1840 | fatal: [localhost]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "deprecations": [{"msg": "Distribution Ubuntu 16.04 on host localhost should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", "version": "2.12"}], "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: setup\n"}
2020-01-09 19:18:07,907 p=wid u=1840 | PLAY RECAP ******************************************************************************
2020-01-09 19:18:07,907 p=wid u=1840 | localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-01-09 19:18:28,728 p=wid u=1880 | [WARNING]: Unable to parse /data/ansible/ex407-preparation/localhost as an inventory
source

2020-01-09 19:18:28,728 p=wid u=1880 | [WARNING]: No inventory was parsed, only implicit localhost is available

2020-01-09 19:18:28,729 p=wid u=1880 | [WARNING]: provided hosts list is empty, only localhost is available. Note that the
implicit localhost does not match 'all'

2020-01-09 19:18:28,855 p=wid u=1880 | PLAY [ansible logrotate] ****************************************************************
2020-01-09 19:18:28,856 p=wid u=1880 | skipping: no hosts matched
2020-01-09 19:18:28,856 p=wid u=1880 | PLAY RECAP ******************************************************************************
2020-01-09 19:19:17,494 p=wid u=1893 | PLAY [ansible logrotate] ****************************************************************
2020-01-09 19:19:17,500 p=wid u=1893 | TASK [Gathering Facts] ******************************************************************
2020-01-09 19:19:17,860 p=wid u=1893 | fatal: [localhost]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "deprecations": [{"msg": "Distribution Ubuntu 16.04 on host localhost should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", "version": "2.12"}], "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: setup\n"}
2020-01-09 19:19:17,862 p=wid u=1893 | PLAY RECAP ******************************************************************************
2020-01-09 19:19:17,862 p=wid u=1893 | localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-01-09 19:19:38,958 p=wid u=1933 | PLAY [ansible logrotate] ****************************************************************
2020-01-09 19:19:38,964 p=wid u=1933 | TASK [Gathering Facts] ******************************************************************
2020-01-09 19:19:39,300 p=wid u=1933 | fatal: [localhost]: FAILED! => {"ansible_facts": {}, "changed": false, "failed_modules": {"setup": {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "deprecations": [{"msg": "Distribution Ubuntu 16.04 on host localhost should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for more information", "version": "2.12"}], "failed": true, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}}, "msg": "The following modules failed to execute: setup\n"}
2020-01-09 19:19:39,301 p=wid u=1933 | PLAY RECAP ******************************************************************************
2020-01-09 19:19:39,301 p=wid u=1933 | localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-01-09 19:20:06,059 p=wid u=1989 | PLAY [ansible logrotate] ****************************************************************
2020-01-09 19:20:06,065 p=wid u=1989 | TASK [nickhammond.logrotate : nickhammond.logrotate | Install logrotate] ****************
2020-01-09 19:20:06,420 p=wid u=1989 | fatal: [localhost]: FAILED! => {"changed": false, "msg": "Could not detect which package manager to use. Try gathering facts or setting the \"use\" option."}
2020-01-09 19:20:06,421 p=wid u=1989 | PLAY RECAP ******************************************************************************
2020-01-09 19:20:06,421 p=wid u=1989 | localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-01-09 19:20:33,968 p=wid u=2069 | PLAY [ansible logrotate] ****************************************************************
2020-01-09 19:20:33,975 p=wid u=2069 | TASK [nickhammond.logrotate : nickhammond.logrotate | Install logrotate] ****************
2020-01-09 19:20:34,236 p=wid u=2069 | [DEPRECATION WARNING]: Distribution Ubuntu 16.04 on host localhost should use 
/usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior 
Ansible releases. A future Ansible release will default to using the discovered platform
 python for this host. See 
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for
 more information. This feature will be removed in version 2.12. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
2020-01-09 19:20:34,237 p=wid u=2069 | fatal: [localhost]: FAILED! => {"ansible_facts": {"discovered_interpreter_python": "/usr/bin/python"}, "changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
2020-01-09 19:20:34,238 p=wid u=2069 | PLAY RECAP ******************************************************************************
2020-01-09 19:20:34,239 p=wid u=2069 | localhost                  : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0   
2020-01-09 19:22:19,739 p=wid u=2135 | PLAY [ansible logrotate] ****************************************************************
2020-01-09 19:22:19,746 p=wid u=2135 | TASK [nickhammond.logrotate : nickhammond.logrotate | Install logrotate] ****************
2020-01-09 19:22:25,346 p=wid u=2135 | [WARNING]: Updating cache and auto-installing missing dependency: python-apt

2020-01-09 19:22:25,350 p=wid u=2135 | [DEPRECATION WARNING]: Distribution Ubuntu 16.04 on host localhost should use 
/usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior 
Ansible releases. A future Ansible release will default to using the discovered platform
 python for this host. See 
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for
 more information. This feature will be removed in version 2.12. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
2020-01-09 19:22:25,350 p=wid u=2135 | ok: [localhost]
2020-01-09 19:22:25,353 p=wid u=2135 | TASK [nickhammond.logrotate : nickhammond.logrotate | Setup logrotate.d scripts] ********
2020-01-09 19:22:25,793 p=wid u=2135 | changed: [localhost] => (item={u'path': u'/data/ansible/ex407-preparation/logs/ansible.log', u'name': u'ansible', u'options': [u'daily', u'size 9M', u'missingok', u'compress', u'delaycompress', u'copytruncate']})
2020-01-09 19:22:25,797 p=wid u=2135 | PLAY RECAP ******************************************************************************
2020-01-09 19:22:25,798 p=wid u=2135 | localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-01-09 19:23:15,424 p=wid u=2508 | PLAY [ansible logrotate] ****************************************************************
2020-01-09 19:23:15,430 p=wid u=2508 | TASK [nickhammond.logrotate : nickhammond.logrotate | Install logrotate] ****************
2020-01-09 19:23:17,013 p=wid u=2508 | [DEPRECATION WARNING]: Distribution Ubuntu 16.04 on host localhost should use 
/usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior 
Ansible releases. A future Ansible release will default to using the discovered platform
 python for this host. See 
https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for
 more information. This feature will be removed in version 2.12. Deprecation warnings 
can be disabled by setting deprecation_warnings=False in ansible.cfg.
2020-01-09 19:23:17,014 p=wid u=2508 | ok: [localhost]
2020-01-09 19:23:17,019 p=wid u=2508 | TASK [nickhammond.logrotate : nickhammond.logrotate | Setup logrotate.d scripts] ********
2020-01-09 19:23:17,501 p=wid u=2508 | changed: [localhost] => (item={u'path': u'/data/ansible/ex407-preparation/logs/ansible.log', u'name': u'ansible', u'options': [u'daily', u'size 9M', u'missingok', u'compress', u'delaycompress', u'copytruncate']})
2020-01-09 19:23:17,503 p=wid u=2508 | PLAY RECAP ******************************************************************************
2020-01-09 19:23:17,503 p=wid u=2508 | localhost                  : ok=2    changed=1    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
2020-01-09 19:35:34,499 p=wid u=2776 | # /data/ansible/ex407-preparation/roles
2020-01-09 19:35:34,502 p=wid u=2776 | - nickhammond.logrotate, master
2020-01-09 19:37:15,597 p=wid u=2810 | No roles match your search.
2020-01-10 01:07:25,049 p=wid u=4436 | localhost | FAILED! => {
    "changed": false, 
    "msg": "useradd: Permission denied.\nuseradd: cannot lock /etc/passwd; try again later.\n", 
    "name": "ansible", 
    "rc": 1
}
2020-01-10 01:07:30,143 p=wid u=4470 | localhost | FAILED! => {
    "changed": false, 
    "msg": "useradd: Permission denied.\nuseradd: cannot lock /etc/passwd; try again later.\n", 
    "name": "ansible", 
    "rc": 1
}
2020-01-10 01:07:35,810 p=wid u=4502 | localhost | FAILED! => {
    "changed": false, 
    "msg": "useradd: Permission denied.\nuseradd: cannot lock /etc/passwd; try again later.\n", 
    "name": "ansible", 
    "rc": 1
}
2020-01-10 01:07:50,075 p=wid u=4547 | localhost | FAILED! => {
    "changed": false, 
    "msg": "useradd: Permission denied.\nuseradd: cannot lock /etc/passwd; try again later.\n", 
    "name": "ansible", 
    "rc": 1
}
2020-01-10 01:08:12,307 p=wid u=4582 | localhost | CHANGED => {
    "changed": true, 
    "comment": "", 
    "create_home": true, 
    "group": 1003, 
    "home": "/home/ansible", 
    "name": "ansible", 
    "shell": "", 
    "state": "present", 
    "system": false, 
    "uid": 1003
}
2020-01-10 01:11:48,991 p=wid u=4645 | localhost | FAILED! => {
    "msg": "template error while templating string: expected token 'end of print statement', got 'up'. String: {{ look\nup('file', '~/.ssh/id_rsa.pub') }}"
}
2020-01-10 01:12:01,362 p=wid u=4653 | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 13] Permission denied: '/home/ansible/.ssh'
2020-01-10 01:12:01,364 p=wid u=4653 | localhost | FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/wid/.ansible/tmp/ansible-tmp-1578593521.1-193707551905725/AnsiballZ_authorized_key.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/wid/.ansible/tmp/ansible-tmp-1578593521.1-193707551905725/AnsiballZ_authorized_key.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/wid/.ansible/tmp/ansible-tmp-1578593521.1-193707551905725/AnsiballZ_authorized_key.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.system.authorized_key', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_authorized_key_payload_GAdAip/ansible_authorized_key_payload.zip/ansible/modules/system/authorized_key.py\", line 682, in <module>\n  File \"/tmp/ansible_authorized_key_payload_GAdAip/ansible_authorized_key_payload.zip/ansible/modules/system/authorized_key.py\", line 677, in main\n  File \"/tmp/ansible_authorized_key_payload_GAdAip/ansible_authorized_key_payload.zip/ansible/modules/system/authorized_key.py\", line 636, in enforce_state\n  File \"/tmp/ansible_authorized_key_payload_GAdAip/ansible_authorized_key_payload.zip/ansible/modules/system/authorized_key.py\", line 344, in keyfile\nOSError: [Errno 13] Permission denied: '/home/ansible/.ssh'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
2020-01-10 01:12:17,592 p=wid u=4683 | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 13] Permission denied: '/home/ansible/.ssh'
2020-01-10 01:12:17,594 p=wid u=4683 | localhost | FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/wid/.ansible/tmp/ansible-tmp-1578593537.32-31019131991325/AnsiballZ_authorized_key.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/wid/.ansible/tmp/ansible-tmp-1578593537.32-31019131991325/AnsiballZ_authorized_key.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/wid/.ansible/tmp/ansible-tmp-1578593537.32-31019131991325/AnsiballZ_authorized_key.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.system.authorized_key', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_authorized_key_payload_nueSja/ansible_authorized_key_payload.zip/ansible/modules/system/authorized_key.py\", line 682, in <module>\n  File \"/tmp/ansible_authorized_key_payload_nueSja/ansible_authorized_key_payload.zip/ansible/modules/system/authorized_key.py\", line 677, in main\n  File \"/tmp/ansible_authorized_key_payload_nueSja/ansible_authorized_key_payload.zip/ansible/modules/system/authorized_key.py\", line 636, in enforce_state\n  File \"/tmp/ansible_authorized_key_payload_nueSja/ansible_authorized_key_payload.zip/ansible/modules/system/authorized_key.py\", line 344, in keyfile\nOSError: [Errno 13] Permission denied: '/home/ansible/.ssh'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
2020-01-10 01:12:55,735 p=wid u=4712 | An exception occurred during task execution. To see the full traceback, use -vvv. The error was: OSError: [Errno 1] Operation not permitted: '/home/widya/.ssh'
2020-01-10 01:12:55,736 p=wid u=4712 | localhost | FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/wid/.ansible/tmp/ansible-tmp-1578593575.47-46880681111913/AnsiballZ_authorized_key.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/home/wid/.ansible/tmp/ansible-tmp-1578593575.47-46880681111913/AnsiballZ_authorized_key.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/wid/.ansible/tmp/ansible-tmp-1578593575.47-46880681111913/AnsiballZ_authorized_key.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.system.authorized_key', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/usr/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_authorized_key_payload_pfXCV0/ansible_authorized_key_payload.zip/ansible/modules/system/authorized_key.py\", line 682, in <module>\n  File \"/tmp/ansible_authorized_key_payload_pfXCV0/ansible_authorized_key_payload.zip/ansible/modules/system/authorized_key.py\", line 677, in main\n  File \"/tmp/ansible_authorized_key_payload_pfXCV0/ansible_authorized_key_payload.zip/ansible/modules/system/authorized_key.py\", line 636, in enforce_state\n  File \"/tmp/ansible_authorized_key_payload_pfXCV0/ansible_authorized_key_payload.zip/ansible/modules/system/authorized_key.py\", line 347, in keyfile\nOSError: [Errno 1] Operation not permitted: '/home/widya/.ssh'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}
2020-01-10 01:13:06,238 p=wid u=4741 | localhost | CHANGED => {
    "changed": true, 
    "comment": null, 
    "exclusive": false, 
    "follow": false, 
    "key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDJnGEpPYO5pwzR4ITZ/6iv1Uyef9belISPsXBBJcM3THnLfBKb33GcizFmL40+D5Tyr513ISB9ahmAnQaKF/iIkK4YChcoRLqc/CbiVM3jtqpVa1Ye1R8zpzcwi4WtVEpZKnnP/koLvxynHkVWQtI7VCeeXasPFCyi4Jt3mavutsV3gYdgp+ZAgRg+rQ8RsBGfpnRSLF088eg/cYJxRy20v4nRnTuxxigRfLJUSs1tg5mEvmt2kIb1rJ1xqkw21uS1NsHpuK6rT4kr5Zb3znOi1xCWzR9RbrkxtTq27K3cZ9h+fELkJ8yP+SQHIi59+P+iMPxfb6G+546szQdNBae9ildnxbYEW5MEkSuyvWP9sJdG1veukXqwWCvWI4nQPfD3HoUIj2wL116zLdrDTAPtaPyDG2h1RMDi6yzVgtMgmS8UJIN8TWENSEjIFTz0dOQINnd2uARNsI04DRZuki60YVnBfeRjEWyEXsgH6w/IOzc4rUoGm5sQMww1fnYZxmM7Gtfzr5rKH1UDzpok0eqmf6VGVayDGG4PxweI3DhVEvTduNRNv5Cn3IJ832Es346CHNnhdneRubz3HIvfENCslPcsbsyjJxWv4HcQ/JfHIMnV2YQsSNUAZsAuGDkLKl58vGTHpV+K0rbi0+0D+soyh8Tgj88P9yX7L1mu3Su/pQ== wid@ubuntu", 
    "key_options": null, 
    "keyfile": "/home/widya/.ssh/authorized_keys", 
    "manage_dir": true, 
    "path": null, 
    "state": "present", 
    "user": "widya", 
    "validate_certs": true
}
2020-01-10 01:19:06,173 p=wid u=4808 | localhost | CHANGED | rc=0 >>
/etc/shadow

2020-01-10 01:19:22,644 p=wid u=4844 | localhost | FAILED | rc=1 >>
cat: /etc/shadow: Permission deniednon-zero return code

2020-01-10 01:19:27,302 p=wid u=4874 | localhost | CHANGED | rc=0 >>
root:$6$KOxaksrL$UpHmwjlTG2tjTvwZKNrCxf2uDGxFuTiA7tVkXNkxzjQ7Y23YnH4JlWKz5vjrK5GcW.XbOPiRs5RC9Cw9TmKdq0:18270:0:99999:7:::
daemon:*:17953:0:99999:7:::
bin:*:17953:0:99999:7:::
sys:*:17953:0:99999:7:::
sync:*:17953:0:99999:7:::
games:*:17953:0:99999:7:::
man:*:17953:0:99999:7:::
lp:*:17953:0:99999:7:::
mail:*:17953:0:99999:7:::
news:*:17953:0:99999:7:::
uucp:*:17953:0:99999:7:::
proxy:*:17953:0:99999:7:::
www-data:*:17953:0:99999:7:::
backup:*:17953:0:99999:7:::
list:*:17953:0:99999:7:::
irc:*:17953:0:99999:7:::
gnats:*:17953:0:99999:7:::
nobody:*:17953:0:99999:7:::
systemd-timesync:*:17953:0:99999:7:::
systemd-network:*:17953:0:99999:7:::
systemd-resolve:*:17953:0:99999:7:::
systemd-bus-proxy:*:17953:0:99999:7:::
syslog:*:17953:0:99999:7:::
_apt:*:17953:0:99999:7:::
messagebus:*:18270:0:99999:7:::
uuidd:*:18270:0:99999:7:::
sshd:*:18270:0:99999:7:::
widysible:$6$CfjrLvwGbzSPGq49$t./6zxk9D16P6J/nq2eBVWQ74aGgzKDr:18270:0:99999:7:::
colord:*:18270:0:99999:7:::
widya:$6$iWapfpVD$05fx.DHA/Um38BCudzsthEuEnWVeT3zSmsASJZx3xC8qFOhMyApffG2gYNt5B6bUhES/CIoIeesXLPAEoghps/:18270:0:99999:7:::
wid:$6$woh1Ol95$/pVLhlzxH1nzWVITBMlboJ12I/EXpzNpkbp3im8a.0nvRdDjJa2ZuRGIlvzoQWbR9cvW4GTCWKkKC60StYM2b1:18270:0:99999:7:::
ansible:!:18270:0:99999:7:::

2020-01-10 01:24:51,271 p=wid u=4933 | localhost | FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'ansible_hostname' is undefined"
}
2020-01-10 01:25:57,230 p=wid u=4947 | localhost | FAILED! => {
    "msg": "The task includes an option with an undefined variable. The error was: 'ansible_hostname' is undefined"
}
2020-01-10 01:26:08,171 p=wid u=4958 | localhost | FAILED! => {
    "changed": false, 
    "msg": "Destination /etc/motd does not exist !", 
    "rc": 257
}
2020-01-10 01:26:39,849 p=wid u=4991 | localhost | CHANGED => {
    "backup": "", 
    "changed": true, 
    "msg": "line added"
}
2020-01-10 11:15:44,878 p=wid u=15357 | [DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad 
characters in group names by default, this will change, but still be user configurable 
on deprecation. This feature will be removed in version 2.10. Deprecation warnings can 
be disabled by setting deprecation_warnings=False in ansible.cfg.
2020-01-10 11:15:44,878 p=wid u=15357 | [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to
see details

2020-01-10 11:15:44,886 p=wid u=15357 |   hosts (5):
2020-01-10 11:15:44,886 p=wid u=15357 |     widf1
2020-01-10 11:15:44,886 p=wid u=15357 |     c7213
2020-01-10 11:15:44,886 p=wid u=15357 |     c7214
2020-01-10 11:15:44,886 p=wid u=15357 |     u16223
2020-01-10 11:15:44,886 p=wid u=15357 |     u16224
2020-01-10 11:16:09,708 p=wid u=15386 | [DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad 
characters in group names by default, this will change, but still be user configurable 
on deprecation. This feature will be removed in version 2.10. Deprecation warnings can 
be disabled by setting deprecation_warnings=False in ansible.cfg.
2020-01-10 11:16:09,709 p=wid u=15386 | [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to
see details

2020-01-10 11:16:09,717 p=wid u=15386 |   hosts (5):
2020-01-10 11:16:09,717 p=wid u=15386 |     widf1
2020-01-10 11:16:09,717 p=wid u=15386 |     c7213
2020-01-10 11:16:09,717 p=wid u=15386 |     c7214
2020-01-10 11:16:09,717 p=wid u=15386 |     u16223
2020-01-10 11:16:09,717 p=wid u=15386 |     u16224
2020-01-10 11:16:32,294 p=wid u=15418 | ERROR! No action selected, at least one of --host, --graph or --list needs to be specified.
2020-01-10 11:16:51,378 p=wid u=15444 | [DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad 
characters in group names by default, this will change, but still be user configurable 
on deprecation. This feature will be removed in version 2.10. Deprecation warnings can 
be disabled by setting deprecation_warnings=False in ansible.cfg.
2020-01-10 11:16:51,378 p=wid u=15444 | [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to
see details

2020-01-10 11:16:51,400 p=wid u=15444 | {
    "10.148.0.2": {
        "hosts": [
            "widf1"
        ]
    }, 
    "35.198.210.9": {
        "hosts": [
            "widf1"
        ]
    }, 
    "_meta": {
        "hostvars": {
            "c7213": {
                "ansible_host": "192.168.98.213"
            }, 
            "c7214": {
                "ansible_host": "192.168.98.214"
            }, 
            "u16223": {
                "ansible_host": "192.168.98.223"
            }, 
            "u16224": {
                "ansible_host": "192.168.98.224"
            }, 
            "widf1": {
                "ansible_ssh_host": "35.198.210.9", 
                "gce_description": "", 
                "gce_id": "5781805978701422576", 
                "gce_image": "ubuntu-1604-xenial-v20200108", 
                "gce_machine_type": "f1-micro", 
                "gce_metadata": {}, 
                "gce_name": "widf1", 
                "gce_network": "default", 
                "gce_private_ip": "10.148.0.2", 
                "gce_public_ip": "35.198.210.9", 
                "gce_status": "RUNNING", 
                "gce_subnetwork": "default", 
                "gce_tags": [
                    "http-server", 
                    "https-server"
                ], 
                "gce_uuid": "9a7edd266ddbbd237b53feff0d2db51450b815ae", 
                "gce_zone": "asia-southeast1-b"
            }
        }
    }, 
    "all": {
        "children": [
            "10.148.0.2", 
            "35.198.210.9", 
            "asia-southeast1-b", 
            "centos", 
            "f1-micro", 
            "network_default", 
            "status_running", 
            "tag_http-server", 
            "tag_https-server", 
            "ubuntu", 
            "ubuntu-1604-xenial-v20200108", 
            "ungrouped", 
            "widmetrocom"
        ]
    }, 
    "asia-southeast1-b": {
        "hosts": [
            "widf1"
        ]
    }, 
    "centos": {
        "hosts": [
            "c7213", 
            "c7214"
        ]
    }, 
    "f1-micro": {
        "hosts": [
            "widf1"
        ]
    }, 
    "network_default": {
        "hosts": [
            "widf1"
        ]
    }, 
    "status_running": {
        "hosts": [
            "widf1"
        ]
    }, 
    "tag_http-server": {
        "hosts": [
            "widf1"
        ]
    }, 
    "tag_https-server": {
        "hosts": [
            "widf1"
        ]
    }, 
    "ubuntu": {
        "hosts": [
            "u16223", 
            "u16224"
        ]
    }, 
    "ubuntu-1604-xenial-v20200108": {
        "hosts": [
            "widf1"
        ]
    }, 
    "widmetrocom": {
        "children": [
            "http-server", 
            "https-server"
        ]
    }
}
2020-01-10 11:17:48,183 p=wid u=15502 | [DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad 
characters in group names by default, this will change, but still be user configurable 
on deprecation. This feature will be removed in version 2.10. Deprecation warnings can 
be disabled by setting deprecation_warnings=False in ansible.cfg.
2020-01-10 11:17:48,183 p=wid u=15502 | [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to
see details

2020-01-10 11:17:48,192 p=wid u=15502 | {
    "10.148.0.2": {
        "hosts": [
            "widf1"
        ]
    }, 
    "35.198.210.9": {
        "hosts": [
            "widf1"
        ]
    }, 
    "_meta": {
        "hostvars": {
            "widf1": {
                "ansible_ssh_host": "35.198.210.9", 
                "gce_description": "", 
                "gce_id": "5781805978701422576", 
                "gce_image": "ubuntu-1604-xenial-v20200108", 
                "gce_machine_type": "f1-micro", 
                "gce_metadata": {}, 
                "gce_name": "widf1", 
                "gce_network": "default", 
                "gce_private_ip": "10.148.0.2", 
                "gce_public_ip": "35.198.210.9", 
                "gce_status": "RUNNING", 
                "gce_subnetwork": "default", 
                "gce_tags": [
                    "http-server", 
                    "https-server"
                ], 
                "gce_uuid": "9a7edd266ddbbd237b53feff0d2db51450b815ae", 
                "gce_zone": "asia-southeast1-b"
            }
        }
    }, 
    "all": {
        "children": [
            "10.148.0.2", 
            "35.198.210.9", 
            "asia-southeast1-b", 
            "f1-micro", 
            "network_default", 
            "status_running", 
            "tag_http-server", 
            "tag_https-server", 
            "ubuntu-1604-xenial-v20200108", 
            "ungrouped"
        ]
    }, 
    "asia-southeast1-b": {
        "hosts": [
            "widf1"
        ]
    }, 
    "f1-micro": {
        "hosts": [
            "widf1"
        ]
    }, 
    "network_default": {
        "hosts": [
            "widf1"
        ]
    }, 
    "status_running": {
        "hosts": [
            "widf1"
        ]
    }, 
    "tag_http-server": {
        "hosts": [
            "widf1"
        ]
    }, 
    "tag_https-server": {
        "hosts": [
            "widf1"
        ]
    }, 
    "ubuntu-1604-xenial-v20200108": {
        "hosts": [
            "widf1"
        ]
    }
}
2020-01-10 11:21:58,219 p=wid u=15759 | [DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad 
characters in group names by default, this will change, but still be user configurable 
on deprecation. This feature will be removed in version 2.10. Deprecation warnings can 
be disabled by setting deprecation_warnings=False in ansible.cfg.
2020-01-10 11:21:58,219 p=wid u=15759 | [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to
see details

2020-01-10 11:21:58,227 p=wid u=15759 | {
    "10.148.0.2": {
        "hosts": [
            "widf1"
        ]
    }, 
    "35.198.210.9": {
        "hosts": [
            "widf1"
        ]
    }, 
    "_meta": {
        "hostvars": {
            "widf1": {
                "ansible_ssh_host": "35.198.210.9", 
                "gce_description": "", 
                "gce_id": "5781805978701422576", 
                "gce_image": "ubuntu-1604-xenial-v20200108", 
                "gce_machine_type": "f1-micro", 
                "gce_metadata": {}, 
                "gce_name": "widf1", 
                "gce_network": "default", 
                "gce_private_ip": "10.148.0.2", 
                "gce_public_ip": "35.198.210.9", 
                "gce_status": "RUNNING", 
                "gce_subnetwork": "default", 
                "gce_tags": [
                    "http-server", 
                    "https-server"
                ], 
                "gce_uuid": "9a7edd266ddbbd237b53feff0d2db51450b815ae", 
                "gce_zone": "asia-southeast1-b"
            }
        }
    }, 
    "all": {
        "children": [
            "10.148.0.2", 
            "35.198.210.9", 
            "asia-southeast1-b", 
            "f1-micro", 
            "network_default", 
            "status_running", 
            "tag_http-server", 
            "tag_https-server", 
            "ubuntu-1604-xenial-v20200108", 
            "ungrouped"
        ]
    }, 
    "asia-southeast1-b": {
        "hosts": [
            "widf1"
        ]
    }, 
    "f1-micro": {
        "hosts": [
            "widf1"
        ]
    }, 
    "network_default": {
        "hosts": [
            "widf1"
        ]
    }, 
    "status_running": {
        "hosts": [
            "widf1"
        ]
    }, 
    "tag_http-server": {
        "hosts": [
            "widf1"
        ]
    }, 
    "tag_https-server": {
        "hosts": [
            "widf1"
        ]
    }, 
    "ubuntu-1604-xenial-v20200108": {
        "hosts": [
            "widf1"
        ]
    }
}
2020-01-10 11:22:16,960 p=wid u=15789 | [DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad 
characters in group names by default, this will change, but still be user configurable 
on deprecation. This feature will be removed in version 2.10. Deprecation warnings can 
be disabled by setting deprecation_warnings=False in ansible.cfg.
2020-01-10 11:22:16,960 p=wid u=15789 | [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to
see details

2020-01-10 11:22:16,981 p=wid u=15789 | {
    "10.148.0.2": {
        "hosts": [
            "widf1"
        ]
    }, 
    "35.198.210.9": {
        "hosts": [
            "widf1"
        ]
    }, 
    "_meta": {
        "hostvars": {
            "c7213": {
                "ansible_host": "192.168.98.213"
            }, 
            "c7214": {
                "ansible_host": "192.168.98.214"
            }, 
            "u16223": {
                "ansible_host": "192.168.98.223"
            }, 
            "u16224": {
                "ansible_host": "192.168.98.224"
            }, 
            "widf1": {
                "ansible_ssh_host": "35.198.210.9", 
                "gce_description": "", 
                "gce_id": "5781805978701422576", 
                "gce_image": "ubuntu-1604-xenial-v20200108", 
                "gce_machine_type": "f1-micro", 
                "gce_metadata": {}, 
                "gce_name": "widf1", 
                "gce_network": "default", 
                "gce_private_ip": "10.148.0.2", 
                "gce_public_ip": "35.198.210.9", 
                "gce_status": "RUNNING", 
                "gce_subnetwork": "default", 
                "gce_tags": [
                    "http-server", 
                    "https-server"
                ], 
                "gce_uuid": "9a7edd266ddbbd237b53feff0d2db51450b815ae", 
                "gce_zone": "asia-southeast1-b"
            }
        }
    }, 
    "all": {
        "children": [
            "10.148.0.2", 
            "35.198.210.9", 
            "asia-southeast1-b", 
            "centos", 
            "f1-micro", 
            "network_default", 
            "status_running", 
            "ubuntu", 
            "ubuntu-1604-xenial-v20200108", 
            "ungrouped", 
            "widmetrocom"
        ]
    }, 
    "asia-southeast1-b": {
        "hosts": [
            "widf1"
        ]
    }, 
    "centos": {
        "hosts": [
            "c7213", 
            "c7214"
        ]
    }, 
    "f1-micro": {
        "hosts": [
            "widf1"
        ]
    }, 
    "network_default": {
        "hosts": [
            "widf1"
        ]
    }, 
    "status_running": {
        "hosts": [
            "widf1"
        ]
    }, 
    "tag_http-server": {
        "hosts": [
            "widf1"
        ]
    }, 
    "tag_https-server": {
        "hosts": [
            "widf1"
        ]
    }, 
    "ubuntu": {
        "hosts": [
            "u16223", 
            "u16224"
        ]
    }, 
    "ubuntu-1604-xenial-v20200108": {
        "hosts": [
            "widf1"
        ]
    }, 
    "widmetrocom": {
        "children": [
            "tag_http-server", 
            "tag_https-server"
        ]
    }
}
2020-01-10 11:22:30,194 p=wid u=15807 | [DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad 
characters in group names by default, this will change, but still be user configurable 
on deprecation. This feature will be removed in version 2.10. Deprecation warnings can 
be disabled by setting deprecation_warnings=False in ansible.cfg.
2020-01-10 11:22:30,194 p=wid u=15807 | [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to
see details

2020-01-10 11:22:30,202 p=wid u=15807 |   hosts (1):
2020-01-10 11:22:30,202 p=wid u=15807 |     widf1
2020-01-10 11:22:48,127 p=wid u=15841 | [DEPRECATION WARNING]: The TRANSFORM_INVALID_GROUP_CHARS settings is set to allow bad 
characters in group names by default, this will change, but still be user configurable 
on deprecation. This feature will be removed in version 2.10. Deprecation warnings can 
be disabled by setting deprecation_warnings=False in ansible.cfg.
2020-01-10 11:22:48,127 p=wid u=15841 | [WARNING]: Invalid characters were found in group names but not replaced, use -vvvv to
see details

2020-01-10 11:22:48,135 p=wid u=15841 |   hosts (1):
2020-01-10 11:22:48,135 p=wid u=15841 |     widf1
